// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBj59R702_UVWC1lzRgXnqjB5Iy7U3lss',
    appId: '1:808153953672:web:f3ef209d1f94576420363d',
    messagingSenderId: '808153953672',
    projectId: 'new-order-app-40c64',
    authDomain: 'new-order-app-40c64.firebaseapp.com',
    storageBucket: 'new-order-app-40c64.firebasestorage.app',
    measurementId: 'G-M0M4THDRV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgl42zZTTWYqF2BaZBEPcWE11qmZDd6Es',
    appId: '1:808153953672:android:cba8ff9115c44dd220363d',
    messagingSenderId: '808153953672',
    projectId: 'new-order-app-40c64',
    storageBucket: 'new-order-app-40c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6VX4QJIDTpWDZTn7ZyJeGdFekqI6fUg',
    appId: '1:808153953672:ios:3c9e1a169a001e1920363d',
    messagingSenderId: '808153953672',
    projectId: 'new-order-app-40c64',
    storageBucket: 'new-order-app-40c64.firebasestorage.app',
    iosBundleId: 'com.example.newOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6VX4QJIDTpWDZTn7ZyJeGdFekqI6fUg',
    appId: '1:808153953672:ios:3c9e1a169a001e1920363d',
    messagingSenderId: '808153953672',
    projectId: 'new-order-app-40c64',
    storageBucket: 'new-order-app-40c64.firebasestorage.app',
    iosBundleId: 'com.example.newOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBj59R702_UVWC1lzRgXnqjB5Iy7U3lss',
    appId: '1:808153953672:web:62643659518c9c0b20363d',
    messagingSenderId: '808153953672',
    projectId: 'new-order-app-40c64',
    authDomain: 'new-order-app-40c64.firebaseapp.com',
    storageBucket: 'new-order-app-40c64.firebasestorage.app',
    measurementId: 'G-15VXQX9FX4',
  );

}